# Generated by Django 4.0 on 2022-12-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('attribute_name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pk', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100, null='Uploaded')),
                ('content', models.FileField(upload_to='dav/datafile/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dav.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='dav.attribute')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_field', to='dav.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dav.datafile'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='pk_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_pk_reference', to='dav.attribute'),
        ),
    ]
